### ISSUE TITLE
Add proper support for domains

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#71]
Currently the language server does have general support for Sphinx domains. There are a [number of places](https://github.com/swyddfa/esbonio/search?q=%22TODO%3A+Implement+proper+domain+handling%22) where support has been hardcoded for the `std` and `python` domains.

There are a number of things we need in order to claim "proper" support
- [x] Being able to suggest roles and directives for all domains under the correct prefix (#101, #104)
- [x] Respect the [`primary_domain`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-primary_domain) setting (#101, #104)
- [x] Ensure the intersphinx completions support domains (#106)
