### ISSUE TITLE
Missing features in v1.0 

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#901]
At this point the `1.0` version of the language server has been in development for [over a year](https://github.com/swyddfa/esbonio/commit/58180da4351a26302ad6e0be7d19d5588b467761), so you might at this point be thinking... when will it be ready?!

I would argue that it's ready today if
- You need modern Python support (`v3.12+`)
- You need modern Sphinx support (`v7+`)
- You need features not available in the stable version
  - MyST support
  - Workspace symbols
  - Synchronised preview scrolling
  - Multi-project / multi-root support

Once you get it running, it is already stable and the features that have been implemented are arguably better than what you will find in the release version. However, compared to the `0.16.x` version there are some features missing.

- [x] Diagnostics
- [x] Document Symbols
- [ ] Completion suggestions for
  - [x] Role names
  - [x] Targets for `:ref:`, `:doc:` etc.
  - [x] Filepaths for `:download:` (#956)
  - [x] Directive names
  - [ ] Directive options
  - [x] Filepaths for `.. image::` etc. (#941)
- [ ] Goto
  - [x] Definition of targets for `:ref:`/`:doc:` (#978)
  - [x] Definition of filepaths for `.. include::` etc. (#978)
  - [ ] Implementation of roles/directives
- [ ] Documentation Hovers
  - [ ] Documentation for roles/directives themselves i.e. how to use `.. toctree::`
  - [x] "What documentation does :class:`HoverContext` link to?" (#1008)
- [x] Document Links (#956)

So, `1.0` will be released once the remaining features have been ported across.

**Comment by hwayne** [comment]
Exciting!

**Comment by alcarney** [comment]
Based on what's left I think waiting for all of the features to be implemented is approaching the point of diminishing returns (if it's not there already! 😅)

I'm going to plan on releasing `v1.0` sometime in October-November, after Python 3.14 and pygls v2 are available. 

This does mean `v1.0` will not include support for Python 3.9 as it will be EOL by then

**Comment by coredumperror** [comment]
Would it be possible to make the 1.0beta version of the VSCode extension available on Open VSX, please? I loved using the pre-release 1.0 back when I ran VS Code, but I now use Cursor, and it can't install extensions from the main VS Code marketplace, and while Esbonio is on Open VSX, the 1.0 beta version isn't.

**Comment by alcarney** [comment]
There isn't a release labelled "1.0 beta" (since the VSCode marketplace at least didn't support beta tags last time I checked), so any version `v0.9x.y` should be considered a 1.0 beta release.

The latest is currently `v0.96.6` which should already be available via Open VSX

**Comment by coredumperror** [comment]
Ahhh, my bad. I had gotten some errors when I first tried to use Esbonio since switching to Cursor, and mistook them for errors caused by being on a pre-1.0 system (which used a config setup that didn't work for my project). I got that fixed, tho, and it's now working properly. Thanks!
